# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

# kotlin
kotlin.code.style=official
kotlinVersion=2.2.20

# progreso
progresoVersion=0.3.1

# fabric
fabric.loom.multiProjectOptimisation=true
minecraftVersion=1.21.11
fabricVersion=0.139.4+1.21.11
fabricLoomVersion=1.14-SNAPSHOT
yarnMappings=1.21.11+build.2
loaderVersion=0.18.2

# other
gsonVersion=2.13.2
websocketVersion=1.6.0
reflectionsVersion=0.10.2
brigadierVersion=1.2.9
shadowVersion=9.3.0