# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

# kotlin
kotlin.code.style=official
kotlinVersion=2.3.0

# progreso
progresoVersion=0.4

# fabric
fabric.loom.multiProjectOptimisation=true
minecraftVersion=26.1.2
fabricVersion=0.149.0+26.1.2
fabricLoomVersion=1.16-SNAPSHOT
loaderVersion=0.19.2

# other
gsonVersion=2.13.2
websocketVersion=1.6.0
reflectionsVersion=0.10.2
brigadierVersion=1.2.9
shadowVersion=9.3.2